import { motion } from 'framer-motion';
import { useNavigate } from 'react-router-dom';
import jsPDF from 'jspdf';
import { 
  Briefcase, Users, Calendar, TrendingUp, Megaphone,
  FileDown, Gem, Target, Radar, Sparkles
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { useToast } from '@/hooks/use-toast';
import { useUserContext } from '@/hooks/useUserContext';
import { useCredits } from '@/hooks/useCredits';
import { TIER_NAMES } from '@/types/multiTenant';
import LegalAdvisorWidget from '@/components/LegalAdvisorWidget';

const stats = [
  { label: "موقعیت‌های فعال", value: "۱۲", change: "+۲", icon: Briefcase },
  { label: "متقاضیان جدید", value: "۴۸", change: "+۱۵", icon: Users },
  { label: "مصاحبه این هفته", value: "۸", change: "+۳", icon: Calendar },
  { label: "استخدام این ماه", value: "۳", change: "+۱", icon: TrendingUp },
];

const IndividualDashboard = () => {
  const navigate = useNavigate();
  const { toast } = useToast();
  const { context } = useUserContext();
  const { credits, loading: creditsLoading } = useCredits();
  
  const hiringHealth = 95;

  const handleExportPDF = () => {
    toast({
      title: "در حال آماده‌سازی گزارش...",
      description: "گزارش PDF به زودی دانلود می‌شود.",
    });

    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    
    doc.setFontSize(20);
    doc.text("Dashboard Report", pageWidth / 2, 20, { align: "center" });
    
    doc.setFontSize(12);
    const currentDate = new Date().toLocaleDateString("fa-IR");
    doc.text(`Date: ${currentDate}`, pageWidth / 2, 30, { align: "center" });
    
    doc.setLineWidth(0.5);
    doc.line(20, 35, pageWidth - 20, 35);
    
    doc.setFontSize(14);
    doc.text("Statistics", 20, 45);
    
    doc.setFontSize(11);
    let yPosition = 55;
    
    doc.text(`Hiring Health: ${hiringHealth}%`, 25, yPosition);
    yPosition += 10;
    
    stats.forEach((stat) => {
      doc.text(`${stat.label}: ${stat.value} (${stat.change})`, 25, yPosition);
      yPosition += 8;
    });
    
    doc.setFontSize(10);
    doc.setTextColor(128);
    doc.text("Generated by hring Dashboard", pageWidth / 2, 280, { align: "center" });
    
    doc.save(`dashboard-report-${new Date().toISOString().split('T')[0]}.pdf`);
    
    toast({
      title: "گزارش آماده شد",
      description: "فایل PDF با موفقیت دانلود شد.",
    });
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-foreground">نمای کلی</h1>
          <p className="text-muted-foreground">خوش آمدید! اینجا خلاصه‌ای از وضعیت استخدام شماست.</p>
        </div>
        
        <div className="flex items-center gap-3">
          <div className="flex items-center gap-2 px-4 py-2 glass-card rounded-xl bg-gradient-to-r from-primary/10 to-accent/10 border border-primary/20">
            <Gem className="w-5 h-5 text-primary" />
            <span className="font-bold text-foreground">
              {creditsLoading ? "..." : credits}
            </span>
            <span className="text-sm text-muted-foreground">GEM</span>
          </div>
          <Badge className="bg-primary/20 text-primary">
            {context?.subscriptionTier ? TIER_NAMES[context.subscriptionTier] : 'رایگان'}
          </Badge>
        </div>
      </div>

      {/* Stats Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-4">
        {/* Hiring Health */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.3 }}
          className="glass-card p-5 flex flex-col items-center justify-center"
        >
          <p className="text-muted-foreground text-sm mb-3">سلامت استخدام</p>
          <div className="relative w-20 h-20">
            <svg className="w-20 h-20 transform -rotate-90" viewBox="0 0 36 36">
              <path
                className="text-secondary"
                strokeWidth="3"
                stroke="currentColor"
                fill="none"
                d="M18 2.0845
                  a 15.9155 15.9155 0 0 1 0 31.831
                  a 15.9155 15.9155 0 0 1 0 -31.831"
              />
              <path
                className="text-primary"
                strokeWidth="3"
                strokeDasharray={`${hiringHealth}, 100`}
                strokeLinecap="round"
                stroke="currentColor"
                fill="none"
                d="M18 2.0845
                  a 15.9155 15.9155 0 0 1 0 31.831
                  a 15.9155 15.9155 0 0 1 0 -31.831"
              />
            </svg>
            <div className="absolute inset-0 flex items-center justify-center">
              <span className="text-lg font-bold text-foreground">٪{hiringHealth}</span>
            </div>
          </div>
          <p className="text-sm text-green-500 mt-2">عالی</p>
        </motion.div>

        {stats.map((stat, index) => (
          <motion.div
            key={stat.label}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.3 + (index + 1) * 0.1 }}
            className="glass-card p-5"
          >
            <div className="flex items-start justify-between">
              <div>
                <p className="text-muted-foreground text-sm">{stat.label}</p>
                <p className="text-3xl font-bold text-foreground mt-1">{stat.value}</p>
              </div>
              <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center">
                <stat.icon className="w-5 h-5 text-primary" />
              </div>
            </div>
            <p className="text-sm text-green-500 mt-2">{stat.change} نسبت به هفته قبل</p>
          </motion.div>
        ))}
      </div>

      {/* Quick Actions */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.7 }}
          className="glass-card p-6"
        >
          <h2 className="text-lg font-semibold text-foreground mb-4">اقدامات سریع</h2>
          <div className="grid grid-cols-2 gap-3">
            <Button 
              className="glow-button text-foreground h-12"
              onClick={() => navigate('/job-description')}
            >
              <Briefcase className="w-4 h-4 ml-2" />
              موقعیت جدید
            </Button>
            <Button 
              variant="outline" 
              className="border-border bg-secondary/50 h-12"
              onClick={() => navigate('/smart-ad-generator')}
            >
              <Megaphone className="w-4 h-4 ml-2" />
              آگهی جدید
            </Button>
            <Button 
              variant="outline" 
              className="border-border bg-secondary/50 h-12"
              onClick={() => navigate('/strategic-compass')}
            >
              <Target className="w-4 h-4 ml-2" />
              قطب‌نمای استراتژی
            </Button>
            <Button 
              variant="outline" 
              className="border-border bg-secondary/50 h-12"
              onClick={handleExportPDF}
            >
              <FileDown className="w-4 h-4 ml-2" />
              گزارش PDF
            </Button>
            <Button 
              variant="outline" 
              className="border-cyan-500/50 bg-cyan-950/30 h-12 hover:bg-cyan-900/50 text-cyan-300"
              onClick={() => navigate('/strategic-radar')}
            >
              <Radar className="w-4 h-4 ml-2" />
              رادار استراتژیک
            </Button>
            <Button 
              variant="outline" 
              className="border-violet-500/50 bg-violet-950/30 h-12 hover:bg-violet-900/50 text-violet-300"
              onClick={() => navigate('/unicorn-lab')}
            >
              <Sparkles className="w-4 h-4 ml-2" />
              آزمایشگاه یونیکورن
            </Button>
          </div>
        </motion.div>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.8 }}
          className="glass-card p-6"
        >
          <h2 className="text-lg font-semibold text-foreground mb-4">مصاحبه‌های امروز</h2>
          <div className="space-y-3">
            {[
              { name: "سارا احمدی", position: "طراح UI/UX", time: "۱۰:۳۰" },
              { name: "محمد رضایی", position: "توسعه‌دهنده فرانت‌اند", time: "۱۴:۰۰" },
              { name: "زهرا کریمی", position: "مدیر محصول", time: "۱۶:۳۰" },
            ].map((interview, i) => (
              <div key={i} className="flex items-center justify-between p-3 bg-secondary/30 rounded-lg">
                <div>
                  <p className="font-medium text-foreground">{interview.name}</p>
                  <p className="text-sm text-muted-foreground">{interview.position}</p>
                </div>
                <span className="text-sm font-medium text-primary">{interview.time}</span>
              </div>
            ))}
          </div>
        </motion.div>
      </div>

      {/* Legal Advisor Widget - for Pro and Plus users */}
      {(context?.subscriptionTier === 'individual_pro' || context?.subscriptionTier === 'individual_plus') && (
        <LegalAdvisorWidget />
      )}
    </div>
  );
};

export default IndividualDashboard;
