from __future__ import annotations

from datetime import UTC, datetime
from hashlib import sha256
from uuid import UUID

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from hring_api.domains.admin.repository import add_audit_log
from hring_api.domains.legal.embedding import EMBEDDING_MODEL, embed_text
from hring_api.domains.legal.ingestion import (
    ExtractedDocument,
    chunk_legal_text,
    fetch_public_source,
    html_to_text,
)
from hring_api.domains.legal.models import LegalSource
from hring_api.domains.legal.repository import (
    count_source_chunks,
    create_source,
    get_source,
    get_source_by_checksum,
    legal_stats,
    list_sources,
    next_source_version,
    replace_source_chunks,
    search_chunks,
)
from hring_api.domains.legal.schemas import (
    LegalHtmlImportRequest,
    LegalImportResponse,
    LegalKnowledgeStats,
    LegalSearchRequest,
    LegalSearchResult,
    LegalSourceMetadata,
    LegalSourceResponse,
    LegalStatsCategory,
    LegalUrlImportRequest,
)


class LegalError(RuntimeError):
    pass


class LegalNotFoundError(LegalError):
    pass


class LegalConflictError(LegalError):
    pass


def _canonical_document_text(value: str) -> str:
    lines = [line.rstrip() for line in value.replace("\r\n", "\n").replace("\r", "\n").split("\n")]
    normalized = "\n".join(lines).strip()
    if len(normalized) < 20:
        raise LegalConflictError("Not enough textual content was found")
    return normalized


def _source_key(metadata: LegalSourceMetadata, document: ExtractedDocument) -> str:
    identity = metadata.source_url or document.filename or metadata.title
    return sha256(identity.strip().casefold().encode("utf-8")).hexdigest()


async def _index_source(
    session: AsyncSession,
    *,
    source: LegalSource,
) -> int:
    source.index_status = "pending"
    await session.flush()
    chunks = chunk_legal_text(
        source.document_text,
        chunk_size=source.chunk_size,
        overlap=source.chunk_overlap,
    )
    indexed: list[dict[str, object]] = []
    seen: set[str] = set()
    for chunk in chunks:
        checksum = sha256(chunk.content.encode("utf-8")).hexdigest()
        if checksum in seen:
            continue
        seen.add(checksum)
        indexed.append(
            {
                "article_number": chunk.article_number,
                "content": chunk.content,
                "content_checksum": checksum,
                "embedding": embed_text(chunk.content),
            }
        )
    if not indexed:
        source.index_status = "failed"
        raise LegalConflictError("No unique legal chunks were produced")
    await replace_source_chunks(session, source=source, chunks=indexed)
    source.embedding_model = EMBEDDING_MODEL
    source.index_status = "ready"
    await session.flush()
    return len(indexed)


async def source_response(
    session: AsyncSession,
    source: LegalSource,
    *,
    chunk_count: int | None = None,
) -> LegalSourceResponse:
    # ``updated_at`` is generated by PostgreSQL on UPDATE. SQLAlchemy expires
    # that attribute after a flush, so refresh it explicitly while we are still
    # inside the async session instead of triggering an implicit sync lazy load.
    await session.refresh(source)
    count = chunk_count
    if count is None:
        count = await count_source_chunks(session, source_id=source.id)
    return LegalSourceResponse(
        id=source.id,
        checksum=source.checksum,
        title=source.title,
        category=source.category,
        source_url=source.source_url,
        source_type=source.source_type,
        original_filename=source.original_filename,
        mime_type=source.mime_type,
        published_at=source.published_at,
        valid_from=source.valid_from,
        valid_to=source.valid_to,
        version=source.version,
        status=source.status,
        chunk_size=source.chunk_size,
        chunk_overlap=source.chunk_overlap,
        embedding_model=source.embedding_model,
        index_status=source.index_status,
        chunk_count=count,
        created_at=source.created_at,
        updated_at=source.updated_at,
    )


async def ingest_document(
    session: AsyncSession,
    *,
    document: ExtractedDocument,
    metadata: LegalSourceMetadata,
    actor_user_id: UUID | None,
    ip_address: str | None,
    request_id: str | None,
) -> LegalImportResponse:
    text = _canonical_document_text(document.text)
    checksum = sha256(text.encode("utf-8")).hexdigest()
    existing = await get_source_by_checksum(session, checksum=checksum, for_update=True)
    if existing is not None and existing.status == "active":
        await add_audit_log(
            session,
            actor_user_id=actor_user_id,
            company_id=None,
            action="legal.source.duplicate",
            resource_type="legal_source",
            resource_id=str(existing.id),
            metadata_json={"checksum": checksum, "request_id": request_id or ""},
            ip_address=ip_address,
        )
        return LegalImportResponse(
            duplicate=True,
            ocr_used=document.ocr_used,
            source=await source_response(session, existing),
            logs=["سند با checksum یکسان قبلاً ثبت شده است؛ رکورد تکراری ساخته نشد."],
        )

    source_key = _source_key(metadata, document)
    if existing is None:
        active_versions = await session.scalars(
            select(LegalSource).where(
                LegalSource.source_key == source_key,
                LegalSource.status == "active",
            )
        )
        for previous in active_versions.all():
            previous.status = "superseded"
        version = await next_source_version(session, source_key=source_key)
        source = await create_source(
            session,
            values={
                "source_key": source_key,
                "checksum": checksum,
                "title": metadata.title,
                "category": metadata.category,
                "source_url": metadata.source_url,
                "source_type": document.source_type,
                "original_filename": document.filename,
                "mime_type": document.mime_type,
                "document_text": text,
                "published_at": metadata.published_at,
                "valid_from": metadata.valid_from,
                "valid_to": metadata.valid_to,
                "version": version,
                "status": "active",
                "chunk_size": metadata.chunk_size,
                "chunk_overlap": metadata.chunk_overlap,
                "embedding_model": EMBEDDING_MODEL,
                "index_status": "pending",
                "created_by": actor_user_id,
            },
        )
        duplicate = False
    else:
        source = existing
        active_versions = await session.scalars(
            select(LegalSource).where(
                LegalSource.source_key == source.source_key,
                LegalSource.status == "active",
                LegalSource.id != source.id,
            )
        )
        for previous in active_versions.all():
            previous.status = "superseded"
        source.title = metadata.title
        source.category = metadata.category
        source.source_url = metadata.source_url
        source.source_type = document.source_type
        source.original_filename = document.filename
        source.mime_type = document.mime_type
        source.document_text = text
        source.published_at = metadata.published_at
        source.valid_from = metadata.valid_from
        source.valid_to = metadata.valid_to
        source.status = "active"
        source.deleted_at = None
        source.chunk_size = metadata.chunk_size
        source.chunk_overlap = metadata.chunk_overlap
        duplicate = True

    chunk_count = await _index_source(session, source=source)
    await add_audit_log(
        session,
        actor_user_id=actor_user_id,
        company_id=None,
        action="legal.source.restore" if duplicate else "legal.source.ingest",
        resource_type="legal_source",
        resource_id=str(source.id),
        metadata_json={
            "checksum": checksum,
            "chunks": chunk_count,
            "ocr_used": document.ocr_used,
            "request_id": request_id or "",
        },
        ip_address=ip_address,
    )
    await session.flush()
    return LegalImportResponse(
        duplicate=duplicate,
        ocr_used=document.ocr_used,
        source=await source_response(session, source, chunk_count=chunk_count),
        logs=[
            f"متن استخراج شد: {len(text):,} کاراکتر",
            f"{chunk_count:,} بخش یکتا با embedding محلی ایندکس شد.",
            "checksum و metadata منبع ثبت شد.",
        ],
    )


async def ingest_html(
    session: AsyncSession,
    *,
    payload: LegalHtmlImportRequest,
    actor_user_id: UUID,
    ip_address: str | None,
    request_id: str | None,
) -> LegalImportResponse:
    document = ExtractedDocument(
        text=html_to_text(payload.html_content),
        mime_type="text/html",
        filename=None,
        source_type="manual-html",
    )
    return await ingest_document(
        session,
        document=document,
        metadata=LegalSourceMetadata.model_validate(payload.model_dump(exclude={"html_content"})),
        actor_user_id=actor_user_id,
        ip_address=ip_address,
        request_id=request_id,
    )


async def ingest_url(
    session: AsyncSession,
    *,
    payload: LegalUrlImportRequest,
    actor_user_id: UUID,
    ip_address: str | None,
    request_id: str | None,
) -> LegalImportResponse:
    document = await fetch_public_source(payload.source_url)
    return await ingest_document(
        session,
        document=document,
        metadata=LegalSourceMetadata.model_validate(payload.model_dump()),
        actor_user_id=actor_user_id,
        ip_address=ip_address,
        request_id=request_id,
    )


async def reindex_source(
    session: AsyncSession,
    *,
    source_id: UUID,
    actor_user_id: UUID,
    chunk_size: int | None,
    chunk_overlap: int | None,
    ip_address: str | None,
    request_id: str | None,
) -> LegalSourceResponse:
    source = await get_source(session, source_id=source_id, for_update=True)
    if source is None:
        raise LegalNotFoundError("Legal source was not found")
    target_size = chunk_size if chunk_size is not None else source.chunk_size
    target_overlap = chunk_overlap if chunk_overlap is not None else source.chunk_overlap
    if target_overlap >= target_size:
        raise LegalConflictError("Chunk overlap must be smaller than chunk size")
    source.chunk_size = target_size
    source.chunk_overlap = target_overlap
    count = await _index_source(session, source=source)
    await add_audit_log(
        session,
        actor_user_id=actor_user_id,
        company_id=None,
        action="legal.source.reindex",
        resource_type="legal_source",
        resource_id=str(source.id),
        metadata_json={
            "chunks": count,
            "embedding_model": EMBEDDING_MODEL,
            "request_id": request_id or "",
        },
        ip_address=ip_address,
    )
    return await source_response(session, source, chunk_count=count)


async def delete_source(
    session: AsyncSession,
    *,
    source_id: UUID,
    actor_user_id: UUID,
    ip_address: str | None,
    request_id: str | None,
) -> None:
    source = await get_source(session, source_id=source_id, for_update=True)
    if source is None:
        raise LegalNotFoundError("Legal source was not found")
    source.status = "deleted"
    source.deleted_at = datetime.now(UTC)
    source.index_status = "pending"
    await replace_source_chunks(session, source=source, chunks=[])
    await add_audit_log(
        session,
        actor_user_id=actor_user_id,
        company_id=None,
        action="legal.source.delete",
        resource_type="legal_source",
        resource_id=str(source.id),
        metadata_json={"vectors_deleted": True, "request_id": request_id or ""},
        ip_address=ip_address,
    )


async def source_history(
    session: AsyncSession,
    *,
    limit: int,
    offset: int,
    include_deleted: bool,
) -> list[LegalSourceResponse]:
    rows = await list_sources(
        session,
        limit=limit,
        offset=offset,
        include_deleted=include_deleted,
    )
    return [await source_response(session, source, chunk_count=count) for source, count in rows]


async def knowledge_stats(session: AsyncSession) -> LegalKnowledgeStats:
    active, chunks, pending, categories = await legal_stats(session)
    return LegalKnowledgeStats(
        active_sources=active,
        indexed_chunks=chunks,
        pending_sources=pending,
        categories=[
            LegalStatsCategory(category=category, sources=sources, chunks=category_chunks)
            for category, sources, category_chunks in categories
        ],
        embedding_model=EMBEDDING_MODEL,
    )


async def search_legal_knowledge(
    session: AsyncSession,
    *,
    payload: LegalSearchRequest,
) -> list[LegalSearchResult]:
    rows = await search_chunks(
        session,
        query=payload.query,
        query_embedding=embed_text(payload.query),
        category=payload.category,
        limit=payload.match_count,
        threshold=payload.match_threshold,
    )
    return [
        LegalSearchResult(
            id=chunk.id,
            source_id=source.id,
            title=source.title,
            content=chunk.content,
            category=source.category,
            source_url=source.source_url,
            article_number=chunk.article_number,
            similarity=round(score, 4),
            source_version=source.version,
            published_at=source.published_at,
        )
        for chunk, source, score in rows
    ]
